#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacie_application_
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="pharmacie")]
	public partial class PharmacieDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertlogin(login instance);
    partial void Updatelogin(login instance);
    partial void Deletelogin(login instance);
    partial void Insertmedicament(medicament instance);
    partial void Updatemedicament(medicament instance);
    partial void Deletemedicament(medicament instance);
    partial void Insertfournisseur(fournisseur instance);
    partial void Updatefournisseur(fournisseur instance);
    partial void Deletefournisseur(fournisseur instance);
    partial void Insertcommande(commande instance);
    partial void Updatecommande(commande instance);
    partial void Deletecommande(commande instance);
    partial void InsertVente(Vente instance);
    partial void UpdateVente(Vente instance);
    partial void DeleteVente(Vente instance);
    #endregion
		
		public PharmacieDataContext() : 
				base(global::Pharmacie_application_.Properties.Settings.Default.pharmacieConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PharmacieDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PharmacieDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PharmacieDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PharmacieDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<login> logins
		{
			get
			{
				return this.GetTable<login>();
			}
		}
		
		public System.Data.Linq.Table<medicament> medicaments
		{
			get
			{
				return this.GetTable<medicament>();
			}
		}
		
		public System.Data.Linq.Table<fournisseur> fournisseurs
		{
			get
			{
				return this.GetTable<fournisseur>();
			}
		}
		
		public System.Data.Linq.Table<commande> commandes
		{
			get
			{
				return this.GetTable<commande>();
			}
		}
		
		public System.Data.Linq.Table<Vente> Ventes
		{
			get
			{
				return this.GetTable<Vente>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.login")]
	public partial class login : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _email;
		
		private string _password;
		
		private string _type;
		
		private string _firstName;
		
		private string _lastName;
		
		private string _CIN;
		
		private System.Data.Linq.Binary _Image;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OnfirstNameChanging(string value);
    partial void OnfirstNameChanged();
    partial void OnlastNameChanging(string value);
    partial void OnlastNameChanged();
    partial void OnCINChanging(string value);
    partial void OnCINChanged();
    partial void OnImageChanging(System.Data.Linq.Binary value);
    partial void OnImageChanged();
    #endregion
		
		public login()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(100)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(50)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstName", DbType="NVarChar(50)")]
		public string firstName
		{
			get
			{
				return this._firstName;
			}
			set
			{
				if ((this._firstName != value))
				{
					this.OnfirstNameChanging(value);
					this.SendPropertyChanging();
					this._firstName = value;
					this.SendPropertyChanged("firstName");
					this.OnfirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastName", DbType="NVarChar(50)")]
		public string lastName
		{
			get
			{
				return this._lastName;
			}
			set
			{
				if ((this._lastName != value))
				{
					this.OnlastNameChanging(value);
					this.SendPropertyChanging();
					this._lastName = value;
					this.SendPropertyChanged("lastName");
					this.OnlastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIN", DbType="NVarChar(20)")]
		public string CIN
		{
			get
			{
				return this._CIN;
			}
			set
			{
				if ((this._CIN != value))
				{
					this.OnCINChanging(value);
					this.SendPropertyChanging();
					this._CIN = value;
					this.SendPropertyChanged("CIN");
					this.OnCINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this.OnImageChanging(value);
					this.SendPropertyChanging();
					this._Image = value;
					this.SendPropertyChanged("Image");
					this.OnImageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.medicament")]
	public partial class medicament : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nom;
		
		private string _Description;
		
		private string _Forme;
		
		private string _Fabricant;
		
		private string _Dosage;
		
		private System.Nullable<int> _Quantité;
		
		private System.Nullable<decimal> _Prix;
		
		private System.Nullable<System.DateTime> _DateExpiration;
		
		private string _Catégorie;
		
		private System.Data.Linq.Binary _Image;
		
		private string _fournisseur;
		
		private EntitySet<commande> _commandes;
		
		private EntitySet<Vente> _Ventes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNomChanging(string value);
    partial void OnNomChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnFormeChanging(string value);
    partial void OnFormeChanged();
    partial void OnFabricantChanging(string value);
    partial void OnFabricantChanged();
    partial void OnDosageChanging(string value);
    partial void OnDosageChanged();
    partial void OnQuantitéChanging(System.Nullable<int> value);
    partial void OnQuantitéChanged();
    partial void OnPrixChanging(System.Nullable<decimal> value);
    partial void OnPrixChanged();
    partial void OnDateExpirationChanging(System.Nullable<System.DateTime> value);
    partial void OnDateExpirationChanged();
    partial void OnCatégorieChanging(string value);
    partial void OnCatégorieChanged();
    partial void OnImageChanging(System.Data.Linq.Binary value);
    partial void OnImageChanged();
    partial void OnfournisseurChanging(string value);
    partial void OnfournisseurChanged();
    #endregion
		
		public medicament()
		{
			this._commandes = new EntitySet<commande>(new Action<commande>(this.attach_commandes), new Action<commande>(this.detach_commandes));
			this._Ventes = new EntitySet<Vente>(new Action<Vente>(this.attach_Ventes), new Action<Vente>(this.detach_Ventes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="NVarChar(100)")]
		public string Nom
		{
			get
			{
				return this._Nom;
			}
			set
			{
				if ((this._Nom != value))
				{
					this.OnNomChanging(value);
					this.SendPropertyChanging();
					this._Nom = value;
					this.SendPropertyChanged("Nom");
					this.OnNomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(255)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Forme", DbType="NVarChar(50)")]
		public string Forme
		{
			get
			{
				return this._Forme;
			}
			set
			{
				if ((this._Forme != value))
				{
					this.OnFormeChanging(value);
					this.SendPropertyChanging();
					this._Forme = value;
					this.SendPropertyChanged("Forme");
					this.OnFormeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fabricant", DbType="NVarChar(100)")]
		public string Fabricant
		{
			get
			{
				return this._Fabricant;
			}
			set
			{
				if ((this._Fabricant != value))
				{
					this.OnFabricantChanging(value);
					this.SendPropertyChanging();
					this._Fabricant = value;
					this.SendPropertyChanged("Fabricant");
					this.OnFabricantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dosage", DbType="NVarChar(50)")]
		public string Dosage
		{
			get
			{
				return this._Dosage;
			}
			set
			{
				if ((this._Dosage != value))
				{
					this.OnDosageChanging(value);
					this.SendPropertyChanging();
					this._Dosage = value;
					this.SendPropertyChanged("Dosage");
					this.OnDosageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantité", DbType="Int")]
		public System.Nullable<int> Quantité
		{
			get
			{
				return this._Quantité;
			}
			set
			{
				if ((this._Quantité != value))
				{
					this.OnQuantitéChanging(value);
					this.SendPropertyChanging();
					this._Quantité = value;
					this.SendPropertyChanged("Quantité");
					this.OnQuantitéChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prix", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Prix
		{
			get
			{
				return this._Prix;
			}
			set
			{
				if ((this._Prix != value))
				{
					this.OnPrixChanging(value);
					this.SendPropertyChanging();
					this._Prix = value;
					this.SendPropertyChanged("Prix");
					this.OnPrixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateExpiration", DbType="Date")]
		public System.Nullable<System.DateTime> DateExpiration
		{
			get
			{
				return this._DateExpiration;
			}
			set
			{
				if ((this._DateExpiration != value))
				{
					this.OnDateExpirationChanging(value);
					this.SendPropertyChanging();
					this._DateExpiration = value;
					this.SendPropertyChanged("DateExpiration");
					this.OnDateExpirationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Catégorie", DbType="NVarChar(50)")]
		public string Catégorie
		{
			get
			{
				return this._Catégorie;
			}
			set
			{
				if ((this._Catégorie != value))
				{
					this.OnCatégorieChanging(value);
					this.SendPropertyChanging();
					this._Catégorie = value;
					this.SendPropertyChanged("Catégorie");
					this.OnCatégorieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this.OnImageChanging(value);
					this.SendPropertyChanging();
					this._Image = value;
					this.SendPropertyChanged("Image");
					this.OnImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fournisseur", DbType="VarChar(50)")]
		public string fournisseur
		{
			get
			{
				return this._fournisseur;
			}
			set
			{
				if ((this._fournisseur != value))
				{
					this.OnfournisseurChanging(value);
					this.SendPropertyChanging();
					this._fournisseur = value;
					this.SendPropertyChanged("fournisseur");
					this.OnfournisseurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="medicament_commande", Storage="_commandes", ThisKey="Id", OtherKey="id_medicament")]
		public EntitySet<commande> commandes
		{
			get
			{
				return this._commandes;
			}
			set
			{
				this._commandes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="medicament_Vente", Storage="_Ventes", ThisKey="Id", OtherKey="ID_medicament")]
		public EntitySet<Vente> Ventes
		{
			get
			{
				return this._Ventes;
			}
			set
			{
				this._Ventes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_commandes(commande entity)
		{
			this.SendPropertyChanging();
			entity.medicament = this;
		}
		
		private void detach_commandes(commande entity)
		{
			this.SendPropertyChanging();
			entity.medicament = null;
		}
		
		private void attach_Ventes(Vente entity)
		{
			this.SendPropertyChanging();
			entity.medicament = this;
		}
		
		private void detach_Ventes(Vente entity)
		{
			this.SendPropertyChanging();
			entity.medicament = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.fournisseur")]
	public partial class fournisseur : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nom;
		
		private string _ville;
		
		private string _adresse;
		
		private string _tel;
		
		private string _email;
		
		private string _fax;
		
		private string _nom_pharmacien_responsable;
		
		private EntitySet<commande> _commandes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnomChanging(string value);
    partial void OnnomChanged();
    partial void OnvilleChanging(string value);
    partial void OnvilleChanged();
    partial void OnadresseChanging(string value);
    partial void OnadresseChanged();
    partial void OntelChanging(string value);
    partial void OntelChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnfaxChanging(string value);
    partial void OnfaxChanged();
    partial void Onnom_pharmacien_responsableChanging(string value);
    partial void Onnom_pharmacien_responsableChanged();
    #endregion
		
		public fournisseur()
		{
			this._commandes = new EntitySet<commande>(new Action<commande>(this.attach_commandes), new Action<commande>(this.detach_commandes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="VarChar(100)")]
		public string nom
		{
			get
			{
				return this._nom;
			}
			set
			{
				if ((this._nom != value))
				{
					this.OnnomChanging(value);
					this.SendPropertyChanging();
					this._nom = value;
					this.SendPropertyChanged("nom");
					this.OnnomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ville", DbType="VarChar(100)")]
		public string ville
		{
			get
			{
				return this._ville;
			}
			set
			{
				if ((this._ville != value))
				{
					this.OnvilleChanging(value);
					this.SendPropertyChanging();
					this._ville = value;
					this.SendPropertyChanged("ville");
					this.OnvilleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adresse", DbType="VarChar(255)")]
		public string adresse
		{
			get
			{
				return this._adresse;
			}
			set
			{
				if ((this._adresse != value))
				{
					this.OnadresseChanging(value);
					this.SendPropertyChanging();
					this._adresse = value;
					this.SendPropertyChanged("adresse");
					this.OnadresseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel", DbType="VarChar(20)")]
		public string tel
		{
			get
			{
				return this._tel;
			}
			set
			{
				if ((this._tel != value))
				{
					this.OntelChanging(value);
					this.SendPropertyChanging();
					this._tel = value;
					this.SendPropertyChanged("tel");
					this.OntelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fax", DbType="VarChar(20)")]
		public string fax
		{
			get
			{
				return this._fax;
			}
			set
			{
				if ((this._fax != value))
				{
					this.OnfaxChanging(value);
					this.SendPropertyChanging();
					this._fax = value;
					this.SendPropertyChanged("fax");
					this.OnfaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom_pharmacien_responsable", DbType="VarChar(100)")]
		public string nom_pharmacien_responsable
		{
			get
			{
				return this._nom_pharmacien_responsable;
			}
			set
			{
				if ((this._nom_pharmacien_responsable != value))
				{
					this.Onnom_pharmacien_responsableChanging(value);
					this.SendPropertyChanging();
					this._nom_pharmacien_responsable = value;
					this.SendPropertyChanged("nom_pharmacien_responsable");
					this.Onnom_pharmacien_responsableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="fournisseur_commande", Storage="_commandes", ThisKey="id", OtherKey="id_fournisseur")]
		public EntitySet<commande> commandes
		{
			get
			{
				return this._commandes;
			}
			set
			{
				this._commandes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_commandes(commande entity)
		{
			this.SendPropertyChanging();
			entity.fournisseur = this;
		}
		
		private void detach_commandes(commande entity)
		{
			this.SendPropertyChanging();
			entity.fournisseur = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.commande")]
	public partial class commande : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_commande;
		
		private System.Nullable<int> _id_fournisseur;
		
		private System.Nullable<int> _id_medicament;
		
		private System.Nullable<System.DateTime> _date_commande;
		
		private System.Nullable<System.DateTime> _date_livraison;
		
		private string _statut;
		
		private System.Nullable<int> _quantite;
		
		private System.Nullable<decimal> _montant_total;
		
		private EntityRef<fournisseur> _fournisseur;
		
		private EntityRef<medicament> _medicament;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_commandeChanging(int value);
    partial void Onid_commandeChanged();
    partial void Onid_fournisseurChanging(System.Nullable<int> value);
    partial void Onid_fournisseurChanged();
    partial void Onid_medicamentChanging(System.Nullable<int> value);
    partial void Onid_medicamentChanged();
    partial void Ondate_commandeChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_commandeChanged();
    partial void Ondate_livraisonChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_livraisonChanged();
    partial void OnstatutChanging(string value);
    partial void OnstatutChanged();
    partial void OnquantiteChanging(System.Nullable<int> value);
    partial void OnquantiteChanged();
    partial void Onmontant_totalChanging(System.Nullable<decimal> value);
    partial void Onmontant_totalChanged();
    #endregion
		
		public commande()
		{
			this._fournisseur = default(EntityRef<fournisseur>);
			this._medicament = default(EntityRef<medicament>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_commande", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_commande
		{
			get
			{
				return this._id_commande;
			}
			set
			{
				if ((this._id_commande != value))
				{
					this.Onid_commandeChanging(value);
					this.SendPropertyChanging();
					this._id_commande = value;
					this.SendPropertyChanged("id_commande");
					this.Onid_commandeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_fournisseur", DbType="Int")]
		public System.Nullable<int> id_fournisseur
		{
			get
			{
				return this._id_fournisseur;
			}
			set
			{
				if ((this._id_fournisseur != value))
				{
					if (this._fournisseur.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_fournisseurChanging(value);
					this.SendPropertyChanging();
					this._id_fournisseur = value;
					this.SendPropertyChanged("id_fournisseur");
					this.Onid_fournisseurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_medicament", DbType="Int")]
		public System.Nullable<int> id_medicament
		{
			get
			{
				return this._id_medicament;
			}
			set
			{
				if ((this._id_medicament != value))
				{
					if (this._medicament.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_medicamentChanging(value);
					this.SendPropertyChanging();
					this._id_medicament = value;
					this.SendPropertyChanged("id_medicament");
					this.Onid_medicamentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_commande", DbType="Date")]
		public System.Nullable<System.DateTime> date_commande
		{
			get
			{
				return this._date_commande;
			}
			set
			{
				if ((this._date_commande != value))
				{
					this.Ondate_commandeChanging(value);
					this.SendPropertyChanging();
					this._date_commande = value;
					this.SendPropertyChanged("date_commande");
					this.Ondate_commandeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_livraison", DbType="Date")]
		public System.Nullable<System.DateTime> date_livraison
		{
			get
			{
				return this._date_livraison;
			}
			set
			{
				if ((this._date_livraison != value))
				{
					this.Ondate_livraisonChanging(value);
					this.SendPropertyChanging();
					this._date_livraison = value;
					this.SendPropertyChanged("date_livraison");
					this.Ondate_livraisonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_statut", DbType="VarChar(50)")]
		public string statut
		{
			get
			{
				return this._statut;
			}
			set
			{
				if ((this._statut != value))
				{
					this.OnstatutChanging(value);
					this.SendPropertyChanging();
					this._statut = value;
					this.SendPropertyChanged("statut");
					this.OnstatutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantite", DbType="Int")]
		public System.Nullable<int> quantite
		{
			get
			{
				return this._quantite;
			}
			set
			{
				if ((this._quantite != value))
				{
					this.OnquantiteChanging(value);
					this.SendPropertyChanging();
					this._quantite = value;
					this.SendPropertyChanged("quantite");
					this.OnquantiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_montant_total", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> montant_total
		{
			get
			{
				return this._montant_total;
			}
			set
			{
				if ((this._montant_total != value))
				{
					this.Onmontant_totalChanging(value);
					this.SendPropertyChanging();
					this._montant_total = value;
					this.SendPropertyChanged("montant_total");
					this.Onmontant_totalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="fournisseur_commande", Storage="_fournisseur", ThisKey="id_fournisseur", OtherKey="id", IsForeignKey=true)]
		public fournisseur fournisseur
		{
			get
			{
				return this._fournisseur.Entity;
			}
			set
			{
				fournisseur previousValue = this._fournisseur.Entity;
				if (((previousValue != value) 
							|| (this._fournisseur.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._fournisseur.Entity = null;
						previousValue.commandes.Remove(this);
					}
					this._fournisseur.Entity = value;
					if ((value != null))
					{
						value.commandes.Add(this);
						this._id_fournisseur = value.id;
					}
					else
					{
						this._id_fournisseur = default(Nullable<int>);
					}
					this.SendPropertyChanged("fournisseur");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="medicament_commande", Storage="_medicament", ThisKey="id_medicament", OtherKey="Id", IsForeignKey=true)]
		public medicament medicament
		{
			get
			{
				return this._medicament.Entity;
			}
			set
			{
				medicament previousValue = this._medicament.Entity;
				if (((previousValue != value) 
							|| (this._medicament.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._medicament.Entity = null;
						previousValue.commandes.Remove(this);
					}
					this._medicament.Entity = value;
					if ((value != null))
					{
						value.commandes.Add(this);
						this._id_medicament = value.Id;
					}
					else
					{
						this._id_medicament = default(Nullable<int>);
					}
					this.SendPropertyChanged("medicament");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vente")]
	public partial class Vente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _ID_medicament;
		
		private System.Nullable<int> _NombreVente;
		
		private System.Nullable<System.DateTime> _DateVente;
		
		private System.Nullable<decimal> _Prix_total;
		
		private EntityRef<medicament> _medicament;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnID_medicamentChanging(System.Nullable<int> value);
    partial void OnID_medicamentChanged();
    partial void OnNombreVenteChanging(System.Nullable<int> value);
    partial void OnNombreVenteChanged();
    partial void OnDateVenteChanging(System.Nullable<System.DateTime> value);
    partial void OnDateVenteChanged();
    partial void OnPrix_totalChanging(System.Nullable<decimal> value);
    partial void OnPrix_totalChanged();
    #endregion
		
		public Vente()
		{
			this._medicament = default(EntityRef<medicament>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_medicament", DbType="Int")]
		public System.Nullable<int> ID_medicament
		{
			get
			{
				return this._ID_medicament;
			}
			set
			{
				if ((this._ID_medicament != value))
				{
					if (this._medicament.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_medicamentChanging(value);
					this.SendPropertyChanging();
					this._ID_medicament = value;
					this.SendPropertyChanged("ID_medicament");
					this.OnID_medicamentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreVente", DbType="Int")]
		public System.Nullable<int> NombreVente
		{
			get
			{
				return this._NombreVente;
			}
			set
			{
				if ((this._NombreVente != value))
				{
					this.OnNombreVenteChanging(value);
					this.SendPropertyChanging();
					this._NombreVente = value;
					this.SendPropertyChanged("NombreVente");
					this.OnNombreVenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateVente", DbType="Date")]
		public System.Nullable<System.DateTime> DateVente
		{
			get
			{
				return this._DateVente;
			}
			set
			{
				if ((this._DateVente != value))
				{
					this.OnDateVenteChanging(value);
					this.SendPropertyChanging();
					this._DateVente = value;
					this.SendPropertyChanged("DateVente");
					this.OnDateVenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prix_total", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Prix_total
		{
			get
			{
				return this._Prix_total;
			}
			set
			{
				if ((this._Prix_total != value))
				{
					this.OnPrix_totalChanging(value);
					this.SendPropertyChanging();
					this._Prix_total = value;
					this.SendPropertyChanged("Prix_total");
					this.OnPrix_totalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="medicament_Vente", Storage="_medicament", ThisKey="ID_medicament", OtherKey="Id", IsForeignKey=true)]
		public medicament medicament
		{
			get
			{
				return this._medicament.Entity;
			}
			set
			{
				medicament previousValue = this._medicament.Entity;
				if (((previousValue != value) 
							|| (this._medicament.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._medicament.Entity = null;
						previousValue.Ventes.Remove(this);
					}
					this._medicament.Entity = value;
					if ((value != null))
					{
						value.Ventes.Add(this);
						this._ID_medicament = value.Id;
					}
					else
					{
						this._ID_medicament = default(Nullable<int>);
					}
					this.SendPropertyChanged("medicament");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
